INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('Joe', 'John', 1, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('Jim', 'Bo', 2, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('Han', 'Solo', 2, 1);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('Brett', 'Barkley', 3, 2);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('Hans', 'Gruber', 3, 3);
INSERT INTO employee (first_name, last_name, role_id, manager_id) VALUES ('Bulbus', 'Tumbledrawers', 4, 1);
INSERT INTO role (title, salary, dept_id) VALUES ('President', 300000, 1);
INSERT INTO role (title, salary, dept_id) VALUES ('VP', 100000, 2);
INSERT INTO role (title, salary, dept_id) VALUES ('Lackey', 50000, 2);
INSERT INTO role (title, salary, dept_id) VALUES ('Wizard', 200000, 3);
INSERT INTO department (name) VALUES ('Wizard');
INSERT INTO department (name) VALUES ('Wizard');
INSERT INTO department (name) VALUES ('Wizard');